// types - FILTRO
export const MOSTRA_TODAS = 'MOSTRA_TODAS';
export const MOSTRA_FINALIZADAS = 'MOSTRA_FINALIZADAS';
export const MOSTRA_ATIVAS = 'MOSTRA_ATIVAS';
export const SET_VISIBILIDADE_FILTRO = 'SET_VISIBILIDADE_FILTRO';