// types - FILTRO
export const MOSTRA_TODAS = 'MOSTRA_TODAS';
export const MOSTRA_FINALIZADAS = 'MOSTRA_FINALIZADAS';
export const MOSTRA_ATIVAS = 'MOSTRA_ATIVAS';
// types - ordem
export const MOSTRA_RECENTES = 'MOSTRA_RECENTES';
export const MOSTRA_ANTIGAS = 'MOSTRA_ANTIGAS';

export const SET_VISIBILIDADE_FILTRO = 'SET_VISIBILIDADE_FILTRO';
export const SET_VISIBILIDADE_ORDEM = 'SET_VISIBILIDADE_ORDEM';